name: Twitter Bot Random Scheduler

on:
  schedule:
    - cron: '15 */4 * * *'  # Every 4 hours
    - cron: '45 2,8,14,20 * * *'  # 4 times daily with offset
  
  workflow_dispatch:
    inputs:
      bot_mode:
        description: 'Bot operation mode'
        required: true
        default: 'standalone'
        type: choice
        options:
          - standalone
          - reply
          - quote
          - thread

jobs:
  twitter-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create environment file
      run: |
        cat > .env << EOF
        TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}
        GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }}
        TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}
        TWITTER_EMAIL=${{ secrets.TWITTER_EMAIL }}
        BOT_USERNAME=${{ secrets.BOT_USERNAME }}
        TARGET_ACCOUNTS=${{ secrets.TARGET_ACCOUNTS }}
        EOF
    
    - name: Validate configuration
      run: python -c "from config import validate_config; validate_config()"
    
    - name: Run bot
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          python main.py ${{ inputs.bot_mode }} --topic "AI and machine learning"
        else
          # Random mode for scheduled runs
          modes=("standalone" "reply" "quote" "thread")
          mode=${modes[$RANDOM % ${#modes[@]}]}
          python main.py $mode --topic "AI and machine learning" --limit 3
        fi
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs-${{ github.run_number }}
        path: bot.log
        retention-days: 7
